import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Convexproviders from "@/components/providers/convexproviders";
import Footer from "@/components/footer";
import Header from "@/components/header";
import Sidebar from "@/components/sidebar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Convexproviders>
          <div className="layout-container">
            <Sidebar />
            <div className="main-content">
              <Header />
              <main>{children}</main>
            </div>
            <Footer />
          </div>
        </Convexproviders>
      </body>
    </html>
  );
}
